local:

  apt:
    installed:
      - build-essential
      - ffmpeg
      - firefox
      - graphviz
      - imagemagick
      - inotify-tools
      - jpegoptim
      - keychain
      - netcat
      - optipng
      - pandoc
      - parallel
      - pngquant
      - rename
      - texlive-latex-recommended
      - tree
      - vim
      - webp
      - youtube-dl
    removed: []

  gradle: 8.1.1

  jetbrainsToolbox: 2.0.2.16660

  nvm: v0.39.4

  servers:
    - name: projects
      ip: 139.144.51.202
