server:

  apt:
    installed:
      - fail2ban
      - ntp
      - ufw
    removed: []

  directories:
    private:
      - '/srv/portfolio'
    public:
      - '/srv/portfolio/public'

  ufw:
    allowed:
      - ssh
      - http
      - https
