server:

  apt:
    installed:
      - fail2ban
      - ntp
      - ufw
    removed: [ ]

  directories:
    private:
      - '/srv/mighty-metrics'
      - '/srv/mighty-metrics/logs'
      - '/srv/mighty-metrics/private'
      - '/srv/portfolio'
      - '/srv/vrsvp'
      - '/srv/vrsvp/logs'
      - '/srv/vrsvp/private'
    public:
      - '/srv/portfolio/public'

  ufw:
    allowed:
      - ssh
      - http
      - https

  mightyMetrics:
    port: 10000
    version: 1.0b

  vrsvp:
    port: 10001
    version: 1.6
