server:

  apt:
    installed:
      - fail2ban
      - ntp
      - ufw
    removed: [ ]

  directories:
    private:
      - '/srv/portfolio'
      - '/srv/vrsvp'
      - '/srv/vrsvp/logs'
      - '/srv/vrsvp/private'
    public:
      - '/srv/portfolio/public'

  ufw:
    allowed:
      - ssh
      - http
      - https

  vrsvp:
    version: 1.4
