- name: Install Caddy key
  get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /etc/apt/trusted.gpg.d/caddy.asc

- name: Add Caddy repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present
    update_cache: yes

- name: Install Caddy
  apt:
    name: caddy
    state: present
