# Packages everything should have
- become: yes
  hosts:
    - all
  roles:
    - apt

# Non-root development environment setup
- become: no
  hosts:
    - local
  roles:
    - local

# Remote machines setup
- become: yes
  hosts:
    - remote
  roles:
    - remote
