# Packages everything should have
- become: yes
  hosts:
    - all
  roles:
    - apt
    - caddy

# Non-root development environment setup
- become: no
  hosts:
    - local
  roles:
    - local-users

# Remote server setup
- become: yes
  hosts:
    - server
  roles:
    - remote-server
