# Packages everything should have
- become: yes
  hosts:
    - all
  roles:
    - common-packages

# Root development environment setup
- become: yes
  hosts:
    - local
  roles:
    - local-development
