# Packages everything should have
- become: yes
  hosts:
    - all
  roles:
    - common-packages
    - caddy

# Root development environment setup
- become: yes
  hosts:
    - local
  roles:
    - local-development

# Non-root development environment setup
- become: no
  hosts:
    - local
  roles:
    - local-users

# Remote server setup
- become: yes
  hosts:
    - server
  roles:
    - remote-server
