- name: Restart rsyslog
  service:
    state: restarted
    name: rsyslog

- name: Restart sshd
  service:
    state: restarted
    name: sshd

- name: Reload systemd
  systemd:
    daemon_reload: true
