- name: All
  include_tasks: all.yml

- name: Local
  include_tasks: local.yml
  when: inventory_hostname in groups["local"]

- name: Remote
  include_tasks: remote.yml
  when: inventory_hostname in groups["remote"]
