- name: Download and upgrade packages with updates
  apt:
    update_cache: true
    upgrade: safe

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ all.apt.installed }}"

- name: Remove packages
  apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ all.apt.removed }}"

- name: Install deb
  apt:
    deb: "{{ item }}"
    state: present
  loop: "{{ all.deb }}"

- name: Local
  include_tasks: local.yml
  when: inventory_hostname in groups["local"]

- name: Server
  include_tasks: server.yml
  when: inventory_hostname in groups["server"]
