- name: SSH config
  template:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    src: ".ssh/config.j2"

- name: Bash config
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    block: "{{ lookup('template', '.bashrc') }}"

- name: Node
  include_tasks: node.yml
