- name: Configs
  include_tasks: configs.yml

- name: Flatpak
  include_tasks: flatpak.yml

- name: Fly
  include_tasks: fly-io.yml

- name: Node
  include_tasks: node.yml

- name: RClone
  include_tasks: rclone.yml

- name: Snap
  include_tasks: snap.yml
