- name: Hostname
  include_tasks: hostname.yml

- name: Firewall
  include_tasks: firewall.yml

- name: SSH
  include_tasks: ssh.yml

- name: Directories
  include_tasks: directories.yml

- name: Mighty Metrics
  import_tasks: mighty-metrics.yml
  tags: mighty-metrics

- name: VRSVP
  import_tasks: vrsvp.yml
  tags: vrsvp

- name: User
  include_tasks: user.yml
