- name: Personal user account
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: /bin/bash
    groups:
      - adm
      - caddy
      - sudo
      - systemd-journal
    append: yes

- name: SSH key for personal user account
  authorized_key:
    user: "{{ ansible_env.SUDO_USER }}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
