- name: Hostname
  include_tasks: hostname.yml

- name: Firewall
  include_tasks: firewall.yml

- name: SSHD
  include_tasks: sshd.yml

- name: Directories
  include_tasks: directories.yml

- name: User
  include_tasks: user.yml
